# cilium-values.yaml
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.244.0.0/16"
  mode: "kubernetes"

k8sServiceHost: "192.168.1.211"
k8sServicePort: 6443

kubeProxyReplacement: "true"
kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"

bpf:
  lbExternalClusterIP: "true"

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

envoy:
  prometheus:
    enabled: true

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
    serviceMonitor:
      enabled: true
  tls:
    enabled: false
